#-------------------------------------------------------------------------------
# Macro to run cmsExp, a G4 application with a standalone CMS detector geometry
#
# Usage: cmsExp run_cmsExp.g4
#
# Requirement: 1) cmsExp.gdml (set CMSEXP_GDML="yourGDML.gdml" to use your own)
#              2) hepevt.data (can be an empty file if generator is particleGun)
#
# Option: 1) physics list: FTFP_BERT (use env PHYSLIST to select other lists)
#         2) production cut : use /run/setCut 1.0 mm to change the cut
#         3) generator type : /mygen/generator [hepEvent|particleGun]
#         4) particle type  : ex) mu- mu+ e- e+ pi- pi+ proton anti_proton
#         5) magnetic field : /mydet/fieldFlux [0.0|3.8] tesla
#                             /mydet/fieldType [parameteric|volumebase|uniform]
#
#-------------------------------------------------------------------------------
# verbosity
#-------------------------------------------------------------------------------
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/run/initialize

#-------------------------------------------------------------------------------
# production cut
#-------------------------------------------------------------------------------
#/run/setCut 1.0 mm (defaultCutValue = 1.0*mm in G4VUserPhysicsList)

#-------------------------------------------------------------------------------
# generator type
#-------------------------------------------------------------------------------
#/mygen/generator hepEvent
#/mygen/generator particleGun

#-------------------------------------------------------------------------------
# set variables if particleGun is selected
#-------------------------------------------------------------------------------
/gun/number     10
/gun/particle   pi+
/gun/energy     10 GeV

#-------------------------------------------------------------------------------
# magnetic field along the +z-axis direction
#-------------------------------------------------------------------------------
/cmsExp/det/setMagField 3.8 tesla

#-------------------------------------------------------------------------------
# number of events
#-------------------------------------------------------------------------------
/run/beamOn    50

#-------------------------------------------------------------------------------
# end of run_cmsExp.g4
#-------------------------------------------------------------------------------
